import { Raleway } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import "./globals.css";
import { Toaster } from '@/components/ui/sonner'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font =  Raleway({ subsets: ['latin'] })

export default function RootLayout({ children }) {
  return (
      <ClerkProvider>
      <html lang="en">
        <body className={font.className}>
          <Toaster />
          <div className="container-full-content">
            {children}
          </div>
        </body>
      </html>
     </ClerkProvider>
  );
}
